const SHOVE_LTT_REG =  0x10;
const SHOVE_REG_REG = 0x11;
const SHOVE_REG_MEM = 0x12;
const SHOVE_MEM_REG = 0x13;

const SMUSH_REG_REG = 0x14;

module.exports = {SHOVE_LTT_REG,SHOVE_REG_REG,
    SHOVE_MEM_REG,SHOVE_REG_MEM,SMUSH_REG_REG};